### ISSUE TITLE
Flink Connector1.2 查询 Srarrocks 出现乱码

### ISSUE THREAD

**Issue by walkhan** [StarRocks/starrocks-connector-for-apache-flink#104]
1.脚本如下：
![image](https://user-images.githubusercontent.com/16821730/173808829-e9d4de04-48fb-4725-bb41-bcd256c6ab3d.png)
2.在sql -client启动yarn session
./yarn-session.sh -jm 1024m -tm 4096m
./sql-client.sh embedded -i etl_starrocks2kafka_assassin_employee_post.sql
3.查询
![image](https://user-images.githubusercontent.com/16821730/173808914-bec1165c-e4c9-4aba-852f-c2796ac071b2.png)
4.结果如下:
![image](https://user-images.githubusercontent.com/16821730/173809036-c4e81cac-a752-4b09-be5f-d56ac91566ed.png)

**Comment by walkhan** [comment]
> 有具体使用的StarRocks版本以及flink-connector-starrocks的版本吗

版本:
Flink1.1.3.6
Starrocks2.2.0
Flink-connecotor-starrocks1.2.2

**Comment by xlfjcg** [comment]
> 版本: Flink1.13.6 Starrocks2.2.0 Flink-connecotor-starrocks1.2.2

这个版本我目前没有复现，你直接从mysql client查sr的数据是正常的吗

**Comment by walkhan** [comment]
> > 版本: Flink1.13.6 Starrocks2.2.0 Flink-connecotor-starrocks1.2.2
> 
> 这个版本我目前没有复现，你直接从mysql client查sr的数据是正常
![image](https://user-images.githubusercontent.com/16821730/173979363-8d26f10d-be3a-43f9-98ec-ede8b90c1d2a.png)
这种方式和dbeaver查询SR都是正常的。只是通过flinkSQL查询出现这种乱码，我在dinky和flink的sql-client中，通过flinkSQL查询都有乱码

**Comment by xlfjcg** [comment]
> > ![image](https://user-images.githubusercontent.com/16821730/173979363-8d26f10d-be3a-43f9-98ec-ede8b90c1d2a.png)
> > 这种方式和dbeaver查询SR都是正常的。只是通过flinkSQL查询出现这种乱码，我在dinky和flink的sql-client中，通过flinkSQL查询都有乱码

我用你截图的环境，测了没发现问题。是不是yarn配的有问题，感觉就是字符集的问题

**Comment by walkhan** [comment]
> > > ![image](https://user-images.githubusercontent.com/16821730/173979363-8d26f10d-be3a-43f9-98ec-ede8b90c1d2a.png)
> > > 这种方式和dbeaver查询SR都是正常的。只是通过flinkSQL查询出现这种乱码，我在dinky和flink的sql-client中，通过flinkSQL查询都有乱码
> 
> 我用你截图的环境，测了没发现问题。是不是yarn配的有问题，感觉就是字符集的问题

但是我用FlinkSQL查询mysql或者hive都是正常的

**Comment by xlfjcg** [comment]
> 但是我用FlinkSQL查询mysql或者hive都是正常的

乱码的是中文吗，还是说有其他什么emoji

**Comment by walkhan** [comment]
> > 但是我用FlinkSQL查询mysql或者hive都是正常的
> 
> 乱码的是中文吗，还是说有其他什么emoji

是中文乱码

**Comment by xlfjcg** [comment]
> 是中文乱码

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/103733994/173985251-3f760721-521e-4b10-9771-935a49ccf060.png">
我只有设置-Dfile.encoding=US-ASCII时，会出现上面的情况。看起来应该是sql-client和sr端都是UTF-8，只有实际执行connector逻辑的是ASCII。如果方便的话，可以用下这个jar测试下
[flink-connector-starrocks-1.2.2_flink-1.13_2.11-test.jar.zip](https://github.com/StarRocks/starrocks-connector-for-apache-flink/files/8915873/flink-connector-starrocks-1.2.2_flink-1.13_2.11-test.jar.zip)

**Comment by xlfjcg** [comment]
> 如果是apache版本，可以在flink-conf.yml中设置 env.java.opts: -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 如果是要集成到CDH，在编译为parcel包的时候，需要在control.sh脚本中添加如下： echo "env.java.opts: -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8" >> $CONF_DIR/flink-conf.properties 编译成功后，乱码问题即可解决

问题解决了吗，是哪块的编码有问题？一般我们这边的环境默认就是utf-8
