### ISSUE TITLE
Implementation of exactly-once semantic in the sink function is totally wrong!

### ISSUE THREAD

**Issue by Myasuka** [StarRocks/starrocks-connector-for-apache-flink#115]
If we refer to the [official doc](https://docs.starrocks.com/en-us/2.0/loading/Flink-connector-starrocks#usage-notes) about exactly-once semantic of starRocks sink connector, we can see descriptions below:
> The overall process is as follows:
> 1. Save data and its label at each checkpoint that is completed at a specific checkpoint interval.
> 2. After data and labels are saved, block the flushing of data cached in the state at the first invoke after each checkpoint is completed.

Unfortunately, the current implementation of such semantic in starRocks connector is totally wrong. It uses Flink's operator state to hold the buffered entities on [sync-phase snapshot](https://github.com/StarRocks/starrocks-connector-for-apache-flink/blob/68501989976722b41c7a867a4baf5736bc2279b2/src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunction.java#L186), and it will flush to starRocks on the next [#invoke](https://github.com/StarRocks/starrocks-connector-for-apache-flink/blob/68501989976722b41c7a867a4baf5736bc2279b2/src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunction.java#L101-L104) method. However, this cannot handle the case that the overall checkpoint failed. If the `checkpoint-42` needs all 3 sub-tasks completed, `subtask-0` succeed with `subtask-1` failed will lead to the `checkpoint-42` failed in the end. However, data will still be sent to starRocks in `subtask-0` in the `#invoke` call after the failed `checkpoint-42`. Thus, once the job failed and restore from the last successful `checkpoint-41`, some data will be stored twice from `subtask-0`.

We should introduce `CheckpointListener` with `notifyCheckpointComplete` to implement such semantics. Even though, we should better leverage two-phase commit semantics to achieve exactly-once for better performance.

**Comment by Myasuka** [comment]
I noticed that starRocks-2.4 has supported two-phase-commit for transactions, what's the timeline to support this feature in flink connector @banmoy ?

**Comment by banmoy** [comment]
@Myasuka We have supported exactly-once based on StarRocks' 2PC in the newly released [1.2.4](https://github.com/StarRocks/starrocks-connector-for-apache-flink/releases/tag/v1.2.4). You can refer to #121 and #131 for the detail of this feature.

**Comment by Myasuka** [comment]
Thanks for the information, I think this issue could be closed as flink-starrocks connector finally implements the exactly-once semantics based on starRocks-2.4.
