### ISSUE TITLE
Flink DateStream 以json格式写入，sink.buffer-flush相关参数 配置后任务无法启动问题

### ISSUE THREAD

**Issue by moutains** [StarRocks/starrocks-connector-for-apache-flink#128]
数据源：kafka
ETL过程：每条json日志解析转化、联查补充后，再转为json字符串；利用StarRocksSink方式写入；
问题：
![image](https://user-images.githubusercontent.com/79699145/192680018-7af38126-c4c4-468c-bf81-479ab7290307.png)
这三个参数配置后，flink任务无法正常启动，去掉之后可以正常启动；

日志也没有明确信息：
[sr-err.log](https://github.com/StarRocks/starrocks-connector-for-apache-flink/files/9661167/sr-err.log)

**Comment by banmoy** [comment]
如果flink jobmanager起来了，发一下jobmanager的日志；如果作业都没有提交成功，发一下client的日志

**Comment by moutains** [comment]
@banmoy 本地测试，找到原因了，sink.buffer-flush.max-bytes的参数配置，最小64M；我配置成了50M，麻烦删掉这个issue吧
