### ISSUE TITLE
jackson依赖只移动了core包

### ISSUE THREAD

**Issue by asan2** [StarRocks/starrocks-connector-for-apache-flink#135]
fasterxml.jackson依赖只移动了core包，没有把anotation和databind一起启动到com.starrocks.shade目录下，导致使用第三方工具时，jackson依赖冲突

**Comment by ChenlingXie** [comment]
+1

**Comment by asan2** [comment]
只能自己手动改pom.xml把anotation和databind给加到com.starrocks.shade

**Comment by WholeWorld-Timothy** [comment]
手动改了之后，会出现其他错误，无法写入数据

**Comment by asan2** [comment]
> 手动改了之后，会出现其他错误，无法写入数据

我挪过去可以正常写入哎，就是pom中再jackson.core下面把另两个复制一下，就一起打包到com.starrocks.shade目录下，这样与原生的包就不会冲突了

**Comment by xlfjcg** [comment]
能发一下报错么，什么三方工具呢 @asan2

**Comment by asan2** [comment]
> 能发一下报错么，什么三方工具呢 @asan2

dinky，开源的工具，其中使用了fasterxml.jackson包，会出现包冲突，starrocks的连接器需要把额外的anotation和databind包也需要一起给挪到com.starrocks.shade下

**Comment by asan2** [comment]
> 能发一下报错么，什么三方工具呢 @asan2

大概是这个报错：
An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.fasterxml.jackson.datatype.jsr310.JavaTimeModule.<init>(JavaTimeModule.java:114)

The following method did not exist:

    com.fasterxml.jackson.databind.module.SimpleModule.<init>(Lcom/fasterxml/jackson/core/Version;)V

**Comment by asan2** [comment]
> 能发一下报错么，什么三方工具呢 @asan2

An attempt was made to call a method that does not exist. The attempt was made from the following location:
    com.fasterxml.jackson.datatype.jsr310.JavaTimeModule.<init>(JavaTimeModule.java:114)
The following method did not exist:
    com.fasterxml.jackson.databind.module.SimpleModule.<init>(Lcom/fasterxml/jackson/core/Version;)V

**Comment by asan2** [comment]
> 能发一下报错么，什么三方工具呢 @asan2

大概报错信息：
  An attempt was made to call a method that does not exist. The attempt was made from the following location:
      com.fasterxml.jackson.datatype.jsr310.JavaTimeModule.<init>(JavaTimeModule.java:114)
  The following method did not exist:
      com.fasterxml.jackson.databind.module.SimpleModule.<init>(Lcom/fasterxml/jackson/core/Version;)V
