### ISSUE TITLE
1.2.4 版本不支持表中字段含有# 号

### ISSUE THREAD

**Issue by LQfly** [StarRocks/starrocks-connector-for-apache-flink#148]
![c279fdde-089e-48be-90de-94bffb31f707](https://user-images.githubusercontent.com/118235836/204998416-571f504d-ed19-4035-b3b0-aebe0ff72094.jpeg)
如果表中字段名含有# 号，会报错。1.2.3 版本是支持的。

**Comment by banmoy** [comment]
@LQfly Can you post your table schema and StarRocks version?

**Comment by LQfly** [comment]
> @LQfly Can you post your table schema and StarRocks version?

![image](https://user-images.githubusercontent.com/118235836/206117097-5757e206-084d-4dc2-9792-4c9d057cbbdc.png)
StarRocks version is 2.4.0
