### ISSUE TITLE
flink sink 到starrocks，如果sink的并行度大于1，怎么保证顺序性？

### ISSUE THREAD

**Issue by zhaoxuezhi888** [StarRocks/starrocks-connector-for-apache-flink#150]
StarRocksSinkOptions.builder()
                        .withProperty("jdbc-url", "jdbc:mysql://192.168.0.126:9030/starrocks_demo")
                        .withProperty("load-url", "192.168.0.126:8030")
                        .withProperty("username", "root")
                        .withProperty("password", "")
                        .withProperty("table-name", "detail")
                        .withProperty("database-name", "test")
                        .withProperty("sink.properties.format", "json")
                        .withProperty("sink.properties.strip_outer_array", "true")
                        // 设置并行度，多并行度情况下需要考虑如何保证数据有序性
                        .withProperty("sink.parallelism", "1")
                        .build());

如果sink并行度>1,请问如何考虑，或者从哪些地方考虑以保证数据有序性？

**Comment by xlfjcg** [comment]
可以使用keyby，比如根据某个主键列进行keyby
