### ISSUE TITLE
sr support flink-1.16 write?

### ISSUE THREAD

**Issue by zck573693104** [StarRocks/starrocks-connector-for-apache-flink#162]
pls give a 1.16 connector.

**Comment by daixiaoyu** [comment]
You can use 1.15 connector for Apache Flink 1.16 , It is compatible

**Comment by christianxiaobai** [comment]
> You can use 1.15 connector for Apache Flink 1.16 , It is compatible
Do you have a corresponding test case, can you take a look at your test case

**Comment by banmoy** [comment]
support officially in [1.2.8](https://github.com/StarRocks/starrocks-connector-for-apache-flink/releases/tag/v1.2.8)
