### ISSUE TITLE
mysql 实时导入starrocks， mysql表包含partition关键字时报错

### ISSUE THREAD

**Issue by liuenguang** [StarRocks/starrocks-connector-for-apache-flink#171]
使用版本：2.4.0
报错截图如下：
![image](https://user-images.githubusercontent.com/27394856/207753143-36cfc344-0f7a-465f-b240-029ba9337df6.png)
SQL执行导入语句如下：
![image](https://user-images.githubusercontent.com/27394856/207753371-fe4a5b83-9c0e-4df7-8045-8307ce6752f0.png)

**Comment by banmoy** [comment]
@liuenguang I will investigate the reason.

**Comment by banmoy** [comment]
@liuenguang Close this issue because it's fixed in #173
