### ISSUE TITLE
unique key不支持删除和主键变更

### ISSUE THREAD

**Issue by Lordeath** [StarRocks/starrocks-connector-for-apache-flink#179]
背景情况：
数据源为MySQL，使用flink做数据同步
starrocks版本为2.4.2
基本的update和insert数据同步功能是正常的，但是有以下情况不符合预期：
举例：
字段B通常是日期，因为在starrocks要做分桶，所以放在了key里面，实际上在MySQL是不作为key的（在flink同步中配置成了key）
1. **情况1，删除数据未同步：**
假设原有的MySQL表的数据为：
主键A    字段B      字段C     字段D
1A               1B          1C           1D
2A               2B          2C           2D
3A               3B          3C           3D
starrocks的表的数据为：
主键A    主键B      字段C     字段D
1A               1B          1C           1D
2A               2B          2C           2D
3A               3B          3C           3D
执行以下SQL：
delete from 表 where 主键A = '1A';
期望starrocks的表的数据为：
主键A    主键B      字段C     字段D
2A               2B          2C           2D
3A               3B          3C           3D
**实际上没有变化**
**starrocks采用primary key时，是可以删除的**

2. **情况2，修改字段未同步**
假设原有的MySQL表的数据为：
主键A    字段B      字段C     字段D
1A               1B          1C           1D
2A               2B          2C           2D
3A               3B          3C           3D
starrocks的表的数据为：
主键A    主键B      字段C     字段D
1A               1B          1C           1D
2A               2B          2C           2D
3A               3B          3C           3D
执行以下SQL：
update 表 set 字段B='X1B' where 主键A = '1A';
期望starrocks的表的数据为：
主键A    主键B      字段C     字段D
1A               X1B          1C           1D
2A               2B          2C           2D
3A               3B          3C           3D
实际上的starrocks的表的数据为：
主键A    主键B      字段C     字段D
1A               1B          1C           1D
1A               X1B          1C           1D
2A               2B          2C           2D
3A               3B          3C           3D
**starrocks采用primary key时，是可以修改的**

希望可以解决这个问题，因为primary key所需的内存太大了，我们上亿的数据查询吃不消用这个模型，改用的unique key
但是unique key有这样的问题

**Comment by banmoy** [comment]
@Lordeath primary key可以打开persistent index试一下？
