### ISSUE TITLE
flinksql  sink to  sr often fail because of nullpoint

### ISSUE THREAD

**Issue by yaobukeji123** [StarRocks/starrocks-connector-for-apache-flink#214]
the data is big
flink 1.15/1.16 sr 2.5.3  connector 1.2.6
this is errors
![image](https://user-images.githubusercontent.com/35523218/232661674-e026eee8-3509-4bf7-a78f-5d5760388e79.png)

**Comment by xfworld** [comment]
check the response data
please Turn on logging and access to relevant return data

My guess is that the data was returned incorrectly and was not processed properly during Json deserialization
![image](https://user-images.githubusercontent.com/5020771/234886171-d74be27c-a0b0-485b-bc37-895a50b34eb5.png)

**Comment by banmoy** [comment]
have fixed, and please upgrade to the newest version
