### ISSUE TITLE
如何写入bitmap字段

### ISSUE THREAD

**Issue by ltylty** [StarRocks/starrocks-connector-for-apache-flink#217]
参考文档中 https://docs.starrocks.io/zh-cn/latest/using_starrocks/Using_bitmap
建表语句如下。 
  CREATE TABLE `page_uv` (
    `page_id` INT NOT NULL COMMENT '页面id',
    `visit_date` datetime NOT NULL COMMENT '访问时间',
    `visit_users` BITMAP BITMAP_UNION NOT NULL COMMENT '访问用户id'
  ) ENGINE=OLAP
  AGGREGATE KEY(`page_id`, `visit_date`)
  DISTRIBUTED BY HASH(`page_id`) BUCKETS 1
  PROPERTIES (
    "replication_num" = "1",
    "storage_format" = "DEFAULT"
  );

用flink starrocks connector如何写入BITMAP 字段visit_users？

**Comment by ltylty** [comment]
找到办法了

CREATE TABLE IF NOT EXISTS page_uv (
page_id INT NOT NULL COMMENT '页面id',
visit_date timestamp NOT NULL COMMENT '访问时间',
visit_users int NOT NULL COMMENT '访问用户id'
) WITH (
    'connector' = 'starrocks',
    'jdbc-url' = 'xxx',
    'load-url' = 'xxx,
    'database-name' = 'xxx',
    'table-name' = 'page_uv',
    'username' = 'xxx
    'password' = 'xxx',
    'sink.buffer-flush.interval-ms' = '60000',
    'sink.properties.format'='json',
    'sink.properties.strip_outer_array'='true',
    'sink.properties.columns' = 'page_id,visit_date,visit_users, visit_users=to_bitmap(visit_users)'
);





 insert into page_uv values  (1, now(), 13);

**Comment by banmoy** [comment]
we added an example https://docs.starrocks.io/en-us/latest/loading/Flink-connector-starrocks#load-data-into-columns-of-bitmap-type
