### ISSUE TITLE
啥时候能支持flink1.17呀？

### ISSUE THREAD

**Issue by fi-ecavc** [StarRocks/starrocks-connector-for-apache-flink#224]
flink1.17已经发布2个月了，什么时候能够支持呢？

**Comment by EMsnap** [comment]
Thanks for asking, it would be an interesting work
Could u please submit a issue or a doc towards it so people can work together to tackle?

**Comment by banmoy** [comment]
support in [1.2.8](https://github.com/StarRocks/starrocks-connector-for-apache-flink/releases/tag/v1.2.8)
