### ISSUE TITLE
多表sink目前有除了smt的解决方案吗？

### ISSUE THREAD

**Issue by TurnoffyourTV** [StarRocks/starrocks-connector-for-apache-flink#226]
如题，在mysql到starrocks的过程中，能否通过代码以库的形式同步到starrocks？如果有能否提供demo？
![image](https://github.com/StarRocks/starrocks-connector-for-apache-flink/assets/54170984/b9bf0df7-978c-44e8-b8b2-8b26144f8f69)

![image](https://github.com/StarRocks/starrocks-connector-for-apache-flink/assets/54170984/b1195f4d-c929-4aed-9bfb-596bb30820b1)

**Comment by zhongshao666** [comment]
看源码，有方案
-------------process:
                StarRocksSinkRowDataWithMeta starRocksSinkRowDataWithMeta = new StarRocksSinkRowDataWithMeta();
                starRocksSinkRowDataWithMeta.setDatabase(database);//指定库
                starRocksSinkRowDataWithMeta.setTable(value.getTableName());//指定表
                starRocksSinkRowDataWithMeta.addDataRow(jsonData.toJSONString());//指定数据
                out.collect(starRocksSinkRowDataWithMeta);

------------main sink:
        StarRocksSinkOptions options = StarRocksSinkOptions.builder()
                .withProperty("jdbc-url", parameterTool.get("jdbc-url"))
                .withProperty("load-url", parameterTool.get("load-url"))
                .withProperty("username", parameterTool.get("username"))
                .withProperty("password", parameterTool.get("password"))
                .withProperty("database-name", parameterTool.get("database-name"))
                .withProperty("table-name", "flink_cdc")//这个参数不生效
                .withProperty("sink.properties.format", "json")
                .withProperty("sink.properties.strip_outer_array", "true")
                .withProperty("sink.parallelism", "1")
                .withProperty("sink.version", "V2")
                .build();

        StarRocksDynamicSinkFunctionV2<StarRocksSinkRowDataWithMeta> sinkFunctionV2 = new StarRocksDynamicSinkFunctionV2<>(options);

        endStream.addSink(sinkFunctionV2).name("StarRocks入库");

**Comment by TurnoffyourTV** [comment]
> options

谢谢解答，不胜感激

**Comment by TurnoffyourTV** [comment]
> 看源码，有方案 -------------process: StarRocksSinkRowDataWithMeta starRocksSinkRowDataWithMeta = new StarRocksSinkRowDataWithMeta(); starRocksSinkRowDataWithMeta.setDatabase(database);//指定库 starRocksSinkRowDataWithMeta.setTable(value.getTableName());//指定表 starRocksSinkRowDataWithMeta.addDataRow(jsonData.toJSONString());//指定数据 out.collect(starRocksSinkRowDataWithMeta);
> 
> ------------main sink: StarRocksSinkOptions options = StarRocksSinkOptions.builder() .withProperty("jdbc-url", parameterTool.get("jdbc-url")) .withProperty("load-url", parameterTool.get("load-url")) .withProperty("username", parameterTool.get("username")) .withProperty("password", parameterTool.get("password")) .withProperty("database-name", parameterTool.get("database-name")) .withProperty("table-name", "flink_cdc")//这个参数不生效 .withProperty("sink.properties.format", "json") .withProperty("sink.properties.strip_outer_array", "true") .withProperty("sink.parallelism", "1") .withProperty("sink.version", "V2") .build();
> 
> ```
>     StarRocksDynamicSinkFunctionV2<StarRocksSinkRowDataWithMeta> sinkFunctionV2 = new StarRocksDynamicSinkFunctionV2<>(options);
> 
>     endStream.addSink(sinkFunctionV2).name("StarRocks入库");
> ```

谢谢解答，不胜感激
