### ISSUE TITLE
Support stream load into BE

### ISSUE THREAD

**Issue by rohankrao** [StarRocks/starrocks-connector-for-apache-flink#244]
Currently, only stream loading into FE work.

If I use BE, I get an error

`20:34:37,213 INFO  com.starrocks.data.load.stream.TransactionStreamLoader        - Transaction commit, label: 6bdf11bb-724a-488e-850a-fa93f44e9307, request : POST http://192.168.29.168:8040/api/transaction/commit HTTP/1.1
20:34:37,220 INFO  com.starrocks.data.load.stream.TransactionStreamLoader        - Transaction committed, lable: 6bdf11bb-724a-488e-850a-fa93f44e9307, body : {
    "Status": "TXN_NOT_EXISTS",
    "Message": "transaction with label 6bdf11bb-724a-488e-850a-fa93f44e9307 not exists"
}
20:34:37,228 INFO  com.starrocks.data.load.stream.DefaultStreamLoader            - Response for get_load_state, label: 6bdf11bb-724a-488e-850a-fa93f44e9307, response status code: 404, response body : `

**Comment by szza** [comment]
Now you can stream-load into BE when `sink.version = v2` and `sink.semantic = at-least-once `

**Comment by rohankrao** [comment]
Still, I am getting the same error. I can see in the logs `com.starrocks.connector.flink.table.sink.SinkFunctionFactory  - Choose sink version V2 for at-least-once.`

**Comment by banmoy** [comment]
@rohankrao For v2, we are using [transaction stream load](https://docs.starrocks.io/en-us/latest/loading/Stream_Load_transaction_interface), and there is a limitation that it must use FE. Why do you  want to use BE directly? Actually FE will choose a BE and redirect to it
