### ISSUE TITLE
multi-segment only supported by pure upsert/delete, so pure upsert after another operation is illegal?

### ISSUE THREAD

**Issue by zouchangzhen** [StarRocks/starrocks-connector-for-apache-flink#257]
multi-segment only supported by pure upsert/delete, so pure upsert after another operation is illegal

**Comment by zouchangzhen** [comment]
{
	"Status": "Fail",
	"BeginTxnTimeMs": 0,
	"Message": "multi-segment only supported by pure upsert/delete, so pure upsert after another operation is illegal",
	"NumberUnselectedRows": 0,
	"CommitAndPublishTimeMs": 0,
	"Label": "c9815b6c-ac5a-4807-bfa1-c0ddbf06d1eb",
	"LoadBytes": 67155382,
	"StreamLoadPutTimeMs": 1,
	"NumberTotalRows": 0,
	"WriteDataTimeMs": 537,
	"TxnId": 24056712,
	"LoadTimeMs": 540,
	"ReadDataTimeMs": 84,
	"NumberLoadedRows": 0,
	"NumberFilteredRows": 0
}

**Comment by banmoy** [comment]
what's the starrocks version you are using? This problem have been fixed in starrocks 2.5.8

**Comment by zouchangzhen** [comment]
ok，thx
