### ISSUE TITLE
Flink MySQL CDC writes to a Starrocks primary key model table, facing data synchronization latency issue

### ISSUE THREAD

**Issue by nathan-szz** [StarRocks/starrocks-connector-for-apache-flink#273]
I discovered that in a multi-table synchronization task, such as multiple 'insert into ...' statements, when testing data insertion into Starrocks, there is a delay of 5 minutes for one particular table. However, when performing a synchronization task for a single table alone, the delay returns to normal, at around 1 minute.

**Comment by nathan-szz** [comment]
Here is my configuration information:
**starrocks:**
'sink.max-retries' = '10',
'sink.buffer-flush.interval-ms' = '30000',
'sink.properties.strip_outer_array' = 'true',
'sink.properties.format' = 'json',
'sink.properties.ignore_json_size' = 'true',
'sink.properties.connectTimeout' = '10000',
'sink.connect.timeout-ms' = '10000',
'sink.version'='V2'

**flink：**

execution.checkpointing.interval: 30000 
state.checkpoints.num-retained: 20        
execution.checkpointing.mode: EXACTLY_ONCE

**Comment by banmoy** [comment]
What's the version of connector?

**Comment by nathan-szz** [comment]
> What's the version of connector?

flink-connector-starrocks-1.2.7_flink-1.15

**Comment by nathan-szz** [comment]
I found reason what cause this bug. it’s not the connector .
