### ISSUE TITLE
StarRocks 3.1.4版本访问hive库中用了udf 的视图报错

### ISSUE THREAD

**Issue by phoenixhadoop** [StarRocks/starrocks-connector-for-apache-flink#306]
当前StarRocks 3.1.4版本访问hive库中用了udf 的视图报错，不确定是不是可以通过某些配置调整能实现正常访问hive中使用了udf的 hive view，请问是否有办法解决？
![Uploading WechatIMG5.jpg…]()

**Comment by phoenixhadoop** [comment]
![Uploading WechatIMG5.jpg…]()

**Comment by phoenixhadoop** [comment]
是hive 中的view创建时 create view VW01 as select  udf1(id) from table01;  其中udf1是hive的udf

**Comment by banmoy** [comment]
You can ask for help in StarRocks project https://github.com/StarRocks/starrocks/issues

**Comment by phoenixhadoop** [comment]
OK , I found that this issue should be submitted in  StarRocks project https://github.com/StarRocks/starrocks/issues ,thanks .

**Comment by phoenixhadoop** [comment]
OK , I found that this issue should be submitted in StarRocks project https://github.com/StarRocks/starrocks/issues ,thanks .

@phoenixhadoop


Add a comment
Comment
 
Add your comment here...
Remember, contributions to this repository should follow our [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone
Development
No branches or pull requests

Notifications
Customize
You’re receiving notifications because you authored the thread.
2 participants
