### ISSUE TITLE
[Feature] flink source无法读取json字段

### ISSUE THREAD

**Issue by wmtbnbo** [StarRocks/starrocks-connector-for-apache-flink#346]
![企业微信截图_17113524952616](https://github.com/StarRocks/starrocks-connector-for-apache-flink/assets/44955013/cd692881-8592-4498-bbf4-8f8b8e071fb5)
当gai该表的data字段为json时，读取数据异常，报错
Failed to open scanner.INVALID_ARGUMENT[Unknown primitive type(27)]

**Comment by jaogoy** [comment]
After #347, JSON should be supported.
