### ISSUE TITLE
当sinkFunction的输入为starRocksSinkRowDataWithMeta时，dataRows里面用list保存的数据只有一条。

### ISSUE THREAD

**Issue by xueqianing** [StarRocks/starrocks-connector-for-apache-flink#84]
多表同步时，需要将source端的数据封装为StarRocksSinkRowDataWithMeta，用Mapfunction将源数据转换为StarRocksSinkRowDataWithMeta实体类时，List里面只保存了一条数据，空间利用率可能不高。
![image](https://user-images.githubusercontent.com/84952208/168551831-ce0de887-3250-4767-bb97-d8a2293e595e.png)

**Comment by TurnoffyourTV** [comment]
@xueqianing 您好，请问多表同步您这边成功了吗，如果成功的话，可否发一个完整demo出来？感激不尽

**Comment by slm998** [comment]
你好 能发个demo出来么 十分感谢
