### ISSUE TITLE
stream load 默认timeout覆盖系统的stream load超时配置

### ISSUE THREAD

**Issue by zhaoawd** [StarRocks/starrocks-connector-for-apache-flink#86]
![image](https://user-images.githubusercontent.com/3120566/169736457-614dc12b-cd71-4145-affd-a1d54906b87f.png)
![image](https://user-images.githubusercontent.com/3120566/169736720-1ce4a66f-0c36-49bb-ac70-24fa0b99f44d.png)

connector的请求会给一个默认60S的timeout配置，而FE在处理时会优先使用request的timeout而不是系统配置的stream load超时选项，导致sink超过1分钟没完成就会停止请求并失败，这个地方的逻辑和FE的冲突了。

**Comment by hffariel** [comment]
可以通过配置 connector的 sink.properties.timeout 来增加时间

**Comment by xiangran0327** [comment]
> > 
> 
> 其实这个是为了防止高并发下 label already exists 情况的 state checking 周期过长而添加的。如果10分钟的话可能大部分任务都会多次failover。

![WechatIMG66](https://github.com/user-attachments/assets/6578f4f6-a018-4955-8213-65fa65800910)
请问这个情况有遇到过吗？be节点重启后，flink connector中碰到label has already been used报错，并且一直在做 Checking label，直到任务失败重启。有什么好的解决办法吗？
