### ISSUE TITLE
限制streamload json格式数据时一批最大为100m

### ISSUE THREAD

**Issue by miaomiaozizi** [StarRocks/starrocks-connector-for-apache-flink#89]
starrocks服务端限制了一次导入JSON格式数据最大为100M，且此参数无法修改，当json数据超过100M时会导致导入失败，希望connector端可以限制EXACTLY_ONCE模式下导入一批JSON数据的大小最大为100M

**Comment by hffariel** [comment]
exactly_once时无法限制body大小，只可以将 checkpoint 周期改小些来缓解下。

**Comment by hffariel** [comment]
可以尝试添加 sink.properties.ignore_json_size=true 来去除 sr 的100M限制
